language: python

branches:
  except:
    - gh-pages

python:
  - "2.7"

install:
  # - pip install .
  # - pip install -r requirements-test.txt
  - pip install tox

# script:
#   - ./run-tests.sh tests

script: tox

services:
  - mongodb

env:
  global:
    - MONGODB_URL=mongodb://localhost:27017/test_data_crawlers

  matrix:
    - TOXENV=py26
    - TOXENV=py27
